// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AgeSuite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('UnderageCola', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€1.25")
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.50")
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.css(".btn-success")).click()
    assert(await driver.findElement(By.css("p")).getText() == "Coming right up! ~bzzzt~")
  })
  it('UnderageBeer', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.00")
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€4.00")
    await driver.findElement(By.css(".btn-success")).click()
    /* {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    } */
    await driver.findElement(By.id("ageInput")).click()
    await driver.findElement(By.id("ageInput")).sendKeys("17")
    await driver.findElement(By.css(".btn-success")).click()
    {
      const elements = await driver.findElements(By.css(".alert-danger"))
      assert(elements.length)
    }
  })
  it('AdultBeer', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.00")
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€4.00")
    await driver.findElement(By.css(".btn-success")).click()
   /* {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    } */
    await driver.findElement(By.id("ageInput")).click()
    await driver.findElement(By.id("ageInput")).sendKeys("19")
    await driver.findElement(By.css(".btn-success")).click()
    assert(await driver.findElement(By.css("p")).getText() == "Coming right up! ~bzzzt~")
  })
})
